package GUI;

/**
 * Contains string literals used to populate various text fields in Hermes' GUI
 */
public class TextFields {
    final static String aboutText = "Coded in 2021 by Marco Seddon-Ferretti, in collaboration with Professor Neil Hyatt, Ms. Lucy Mottram and Dr Martin Stennett.\n\nHERMES is a graphical user interface tool, to enable visualisation, pre-processing and energy recalibration of laboratory XAS data from Rowland circle spectrometers, for import into software such as ATHENA for further analysis.\n\nHERMES software was developed with resources of EPSRC Impact Acceleration Account at the University of Sheffield under grant EP/R511754/1 and the HADES/MIDAS facility at the University of Sheffield established with financial support from EPSRC and BEIS, under grant EP/T011424/1.\n\nSource code and documentation for Hermes can be found at:\nhttps://github.com/xasheffield/hermes\n\nHERMES is distributed under an MIT Licence. No warranty is provided against damage caused by use of this software. \n\nVersion 1.0.0";
    final static String licenceText = "HERMES is distributed under the following licence. \n\nMIT License  Copyright (c) [2021] [Marco Seddon-Ferretti]  \n\nPermission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the \"Software\"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:  \n\nThe above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.  \n\nTHE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.";
}
