/**
 * Represents the various types of files loaded and generated by the software.
 * I0, I0b, It, Itb are experimental data
 * ABSORPTION and CORRECTED are processed files generated by the user on tabs 2 and 3 of the GUI respectively
 */
package Data.Models;

public enum MeasurementType {
    //TODO fix hardcoded label names in measurementTypeComboBox
    I0("I0"), I0b("I0 leakage"), It("It"), Itb("It leakage"), ABSORPTION("Absorption"), CORRECTED("Corrected");

    public final String label;

    MeasurementType(String label) {
        this.label = label;
    }

    public static MeasurementType labelToValue(String label) throws RuntimeException{
        for (MeasurementType type: MeasurementType.values()) {
            if (type.label.equals(label)) {
                return type;
            }
        }
        throw new RuntimeException("Invalid label for MeasurementType");
    }
}
